himonoco/bookmaker/urls.py
from django.urls import include, path
from .views import EventListView, GamesListView, GameDetailView, CreateExpectationView

urlpatterns = [
    path("", EventListView.as_view(), name="events"),
    path("<int:event>/", GamesListView.as_view(), name="games"),
    path("<int:event>/<slug:pk>/", GameDetailView.as_view(), name="game_detail"),
    path("<int:event>/<slug:pk>/post/", CreateExpectationView.as_view(), name="create_expectation")
]

himonoco/himonoco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("bookmaker.urls")),
    path('admin/', admin.site.urls),
]

himonoco/bookmaker/models.py
from django.db import models

# Create your models here.


class Player(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=100)
    players = models.ManyToManyField(to=Player)

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField(max_length=100)
    event = models.ForeignKey(to=Event, on_delete=models.CASCADE)
    win_point = models.IntegerField()
    winner = models.ForeignKey(Player, on_delete=models.CASCADE, null=True, blank=True, related_name="winner")

    def __str__(self):
        return self.name


class Spectator(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def points(self, event: Event):
        expectations = Expectation.objects.filter(game__event=event, spectator=self).select_related("game__winner").select_related("expected_winner")
        current_sum = sum([expectation.calc_point() for expectation in expectations])
        return current_sum


class Expectation(models.Model):
    spectator = models.ForeignKey(to=Spectator, on_delete=models.CASCADE)
    game = models.ForeignKey(to=Game, on_delete=models.CASCADE)
    expected_winner = models.ForeignKey(Player, on_delete=models.CASCADE)

    class Meta:
        unique_together = ["spectator", "game"]

    def __str__(self):
        return f"{self.game.name} - {self.expected_winner.name}({self.spectator.name})"

    def calc_point(self):
        lose_point = 0
        if self.game.winner is not None:
            if self.expected_winner == self.game.winner:
                return self.game.win_point

        return lose_point

himonoco/bookmaker/views.py
from django.http import HttpResponseRedirect, Http404, HttpResponseNotFound
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, RedirectView
from django.shortcuts import render

from .models import Event, Game, Player, Spectator, Expectation
import urllib.parse

# Create your views here.


class EventListView(ListView):
    template_name = "bookmaker/events.html"
    model = Event


class GamesListView(ListView):
    template_name = "bookmaker/games.html"
    model = Game

    def get_queryset(self):
        event = Event.objects.get(id=self.kwargs["event"])  # type: Event
        return Game.objects.filter(event=event).select_related("event").select_related("winner")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # ここsqliteだとdistinctが動作しない
        event = Event.objects.get(id=self.kwargs["event"])
        distinct_spectators = Spectator.objects.filter(expectation__game__event=event).distinct()
        ordered_distinct_spectators = sorted(distinct_spectators,
                                             key=lambda x: x.points(event=event),
                                             reverse=True)
        context['spectators'] = ordered_distinct_spectators
        context["event"] = event
        return context


class GameDetailView(DetailView):
    template_name = "bookmaker/game.html"
    model = Game

    def get_context_data(self, **kwargs):
        context = super(GameDetailView, self).get_context_data(**kwargs)
        context["spec_name"] = urllib.parse.unquote(self.request.COOKIES.get("spec_name", ""))
        return context


class CreateExpectationView(View):
    def post(self, request, *args, **kwargs):
        spectator_name = request.POST["spectator-name"]
        player_id = int(request.POST["player-id"])
        game_id = int(request.POST["game-id"])

        spectator_obj = Spectator.objects.get_or_create(name=spectator_name)[0]
        player_obj = Player.objects.get(id=player_id)
        game_obj = Game.objects.get(id=game_id)

        if game_obj.winner is not None:
            return HttpResponseNotFound("すでに投票が締め切られています。次は頑張りましょう。")

        if Expectation.objects.filter(spectator=spectator_obj, game=game_obj).count() == 0:
            Expectation.objects.create(
                spectator=spectator_obj,
                expected_winner=player_obj,
                game=game_obj
            )
        else:
            expectation = Expectation.objects.get(
                spectator=spectator_obj,
                game=game_obj
            )

            expectation.expected_winner = player_obj
            expectation.save()

        url = reverse("game_detail", kwargs={"event": game_obj.event.id, "pk": game_obj.id})
        response = HttpResponseRedirect(url)

        response.set_cookie("spec_name", urllib.parse.quote(spectator_name))

        return response

himonoco/bookmaker/templates/bookmaker/events.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ヒモのこ賭博場</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
<div class="row container d-flex align-items-end">
    <h1 class="col-9">
    ヒモのこ賭博場
    </h1>
    <div class="col mb-1">
        <a href="./admin/bookmaker/" class="float-right">
            管理画面
        </a>
    </div>
</div>
<table class="table">
    {% for event in object_list  %}
        <tr>
            <td>
                <a href="./{{ event.id }}/">
                    {{ event.name }}
                </a>
            </td>
        </tr>
    {% endfor %}
</table>
</div>

</body>
</html>

himonoco/bookmaker/templates/bookmaker/game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ヒモのこ賭博場</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"
            integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">

    <h1>
        {{ object.name }}
    </h1>
    {% if not object.winner %}
        <div class="card mx-3 my-3 container">
            <h3 class="card-title">
                投票する
            </h3>
            <form action="./post/" method="post">
                {% csrf_token %}
                <div class="input-group mx-3 row">
                    <div class="input-group-prepend">
                        <span class="input-group-text">自分の名前</span>
                    </div>
                    <input type="text"
                           class="form-control"
                           placeholder="自分の名前"
                           aria-label="自分の名前"
                           width="100%"
                           id="spectator-name"
                           name="spectator-name"
                           size="15"
                           value="{{ spec_name }}"
                    >
                </div>
                <div class="input-group mx-3 row">
                    <div class="input-group-prepend">
                        <span class="input-group-text">投票先</span>
                    </div>
                    <select class="form-control" aria-label="投票先" id="player-id" name="player-id">
                        {% for player in object.event.players.all %}
                            <option value="{{ player.id }}">{{ player.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <input type="hidden" value="{{ object.id }}" name="game-id">
                <button class="btn btn-primary px-5 mx-3 mt-2 mb-3" style="width: 100%">予想を送信</button>
            </form>
        </div>
    {% endif %}

    <h2>勝者：
        {% if object.winner %}
            {{ object.winner.name }}
        {% else %}
            未定
        {% endif %}
    </h2>
    <table class="table">
        <tr>
            <th>
                観客の名前
            </th>
            <th>
                予想勝者
            </th>
        </tr>
        {% for expectation in object.expectation_set.all %}
            <tr{% if expectation.expected_winner.name == object.winner.name %} class="table-success" {% endif %}>
                <td>
                    {{ expectation.spectator.name }}
                </td>
                <td>
                    {{ expectation.expected_winner.name }}
                </td>
            </tr>
        {% endfor %}
</table>
</div>
</body>
</html>

himonoco/bookmaker/templates/bookmaker/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ヒモのこ賭博場</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"
            integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <h1>
        {{ event.name }}
    </h1>
    <table class="table">
        {% for game in object_list %}
            <tr>
                <td>
                    <a href="{% url 'game_detail' event=game.event.id pk=game.id %}">
                        {{ game.name }}
                    </a>
                </td>
                <td>
                    <a href="{% url 'game_detail' event=game.event.id pk=game.id %}">
                       {% if not game.winner %}投票受付中！{% endif %}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <h2>総合成績</h2>
    <table class="table">
        <tr>
            <th>
                観戦者名
            </th>
            <th>
                合計点
            </th>
            <th>
                予想の内訳
            </th>
        </tr>
        {% load call_methods %}

        <tr>
            {% for spectator in spectators %}
                <td>
                    {{ spectator.name }}
                </td>
                <td>
                    {% call_method spectator "points" event %}点
                </td>
                <td>
                    あとで作る
                </td>

                </tr>
            {% endfor %}
    </table>
</div>
</body>
</html>